Perks and benefits
meilisearch/landing pull request #578
Opened 2022-11-15 13:11 UTC by mdubus

# Pull Request

## Related issue
Closes #482

## What does this PR do?
- Addition of the new block "Perks & benefits"
- Addition of the matching story inside Storybook
- New hook 

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-11-15 20:27 UTC, bidoubiwa commented on src/hooks/useWindowSize.js
> +  })
```suggestion
  })
  
```

2022-11-16 11:33 UTC, bidoubiwa requested changes
the worst review ever 😂

2022-11-16 11:33 UTC, bidoubiwa commented on src/hooks/useWindowSize.js
> +  }, [])
```suggestion
  }, [])
  
```

2022-11-16 13:36 UTC, mdubus commented
bors merge

2022-11-16 13:38 UTC, merged